# Dockerfiles pipeline
variables:
  dockerId: kubistmi
  imageName: pyspark

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: docker build -t $(dockerId)/$(imageName):latest .
  displayName: 'Building the executor image'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName):latest
  displayName: 'Publishing executor image to DockerHub' 