# Dockerfiles pipeline
variables:
  dockerId: kubistmi
  executorName: pyspark
  driverName: pyspark_driver

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: cd executor && docker build -t $(dockerId)/$(executorName):latest .
  displayName: 'Building the executor image'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(executorName):latest
  displayName: 'Publishing executor image to DockerHub' 


- script: cd driver && docker build -t $(dockerId)/$(driverName):latest .
  displayName: 'Building the driver image'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(driverName):latest
  displayName: 'Publishing driver image to DockerHub' 